name: Prueba unitaria

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas unitarias
        run: npm test

      - name: Subir resultados de las pruebas
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./coverage/coverage-report/lcov.info
